### ISSUE TITLE
GlowSize not working

### ISSUE THREAD

**Issue by gifffert** [SMehranB/GlowNeonButton#4]
Hello great library. However, I ran into the problem that setting xml pressedGlowSize and unpressedGlowSize have no effect. There is a solution?

**Comment by SMehranB** [comment]
Hi, Thanks a lot for your interest in the library. 
None of the buttons have the attributes pressedGlowSize and unpressedGlowSize. 
As for the click effect, there is only a ripple effect on click.
If you explain what exactly it is that you want to achieve, I might be able to include it in a later version.

Extra note:
The glow effect only changes in size when you disable or enable the button using the enableWithAnimation() or disableWithAnimation() functions.

**Comment by SMehranB** [comment]
closed due to inactivity
